### ISSUE TITLE
Can't find tool_demo.py

### ISSUE THREAD

**Issue by ameeratgithub** [daveshap/OpenAI_Agent_Swarm#148]
How to run tool_demo.py? I'm unable to find one

**Comment by RomanGoEmpire** [comment]
@ameeratgithub 
tool_demo.py was removed, because there is a new version:
Please read the [README](https://github.com/daveshap/OpenAI_Agent_Swarm/blob/main/agents/tool_maker/README.md).
You have to run the [unit manager (https://github.com/daveshap/OpenAI_Agent_Swarm/blob/main/agents/tool_maker/unit_manager.py)
